### ISSUE TITLE
Is the code used in "Ranking the effectiveness of worldwide COVID-19 government interventions" available?

### ISSUE THREAD

**Issue by walterra** [amel-github/CCCSL-Codes#1]
Thank you for creating the `covid19-interventionmeasures` dataset and these examples, it's a fantastic resource.

If was wondering if the code used for the paper "Ranking the effectiveness of worldwide COVID-19 government interventions" is available somewhere too? It would be great if the applied ML approaches were somehow reproducible.

**Comment by dgarcia-eu** [comment]
Thanks for your kind words! The repository with codes for that paper is here: https://github.com/complexity-science-hub/ranking_npis
Best,
David
